name: sim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.7
  firebase_core: ^1.13.0
  fluttertoast: ^8.0.8
  cupertino_icons: ^0.1.3
  syncfusion_flutter_charts: ^20.1.48
  mailer: ^5.1.0
  animated_splash_screen: ^1.2.0
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.13
  #tflite: ^1.1.2


  http: ^0.13.0
  telephony: ^0.2.0
  flutter_icons: ^1.1.0
  animated_bottom_navigation_bar: ^0.2.1
  fl_chart: ^0.12.2
  percent_indicator: "^2.1.7+2"
  email_auth: ^1.0.0
  reactive_forms: ^11.0.1
  get: ^4.3.8
  onesignal_flutter: ^3.0.0

  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.4.1
  rxdart: ^0.27.3
  flutter_datetime_picker: ^1.5.1
  android_alarm_manager_plus: ^2.0.5





    # When depending on this package from a real application you should use:
    #   telephony: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
  # The example app is bundled with the plugin so we use a path dependency on
  # the parent directory to use the current plugin's version.


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0


  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  #uses-material-design: true
flutter:
  # To add assets to your application, add an assets section, like this:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
